% AUTO-GENERATED FROM app.mlapp BY export_app_source.m.
% DO NOT EDIT THIS FILE DIRECTLY.
% Regenerate with: matlab -batch "export_app_source"

classdef app_exported < matlab.apps.AppBase

    % Properties that correspond to app components
    properties (Access = public)
        UIFigure                        matlab.ui.Figure
        HomePanel                       matlab.ui.container.Panel
        SubjectIDEditField              matlab.ui.control.EditField
        SubjectIDEditFieldLabel         matlab.ui.control.Label
        SleepDataPreprocessingAppLabel  matlab.ui.control.Label
        ContinueButton                  matlab.ui.control.Button
        SelectedEEGEMGPathTextArea      matlab.ui.control.TextArea
        SelectedTDTFolderTextArea       matlab.ui.control.TextArea
        AddViewpointSireniaFileButton   matlab.ui.control.Button
        AddTDTFolderButton              matlab.ui.control.Button
        ProgressPanel                   matlab.ui.container.Panel
        SaveFileButton                  matlab.ui.control.Button
        ProgressTextArea                matlab.ui.control.TextArea
        TDTBiosignalsPanel              matlab.ui.container.Panel
        EventPeriodNameLabel            matlab.ui.control.Label
        Label                           matlab.ui.control.Label
        TTLChannelDropDown_2Label_2     matlab.ui.control.Label
        TTLChannelDropDown_2Label       matlab.ui.control.Label
        ChannelDField                   matlab.ui.control.EditField
        ChannelDEditFieldLabel_2        matlab.ui.control.Label
        ChannelCField                   matlab.ui.control.EditField
        ChannelCEditFieldLabel_2        matlab.ui.control.Label
        ChannelBField                   matlab.ui.control.EditField
        ChannelBEditFieldLabel_2        matlab.ui.control.Label
        ChannelAField                   matlab.ui.control.EditField
        ChannelAEditFieldLabel_2        matlab.ui.control.Label
        InvertDCheckBox                 matlab.ui.control.CheckBox
        InvertCCheckBox                 matlab.ui.control.CheckBox
        InvertBCheckBox                 matlab.ui.control.CheckBox
        InvertACheckBox                 matlab.ui.control.CheckBox
        InvertLabel                     matlab.ui.control.Label
        SubjectIDLabel                  matlab.ui.control.Label
        BackButton                      matlab.ui.control.Button
        SignalNameLabel                 matlab.ui.control.Label
        ReferenceChannelLabel           matlab.ui.control.Label
        ContinueButton2                 matlab.ui.control.Button
        EventPeriodNameEditField        matlab.ui.control.EditField
        EventPeriodChannelDropDown      matlab.ui.control.DropDown
        TTLChannelDropDown              matlab.ui.control.DropDown
        RefChannelDDropDown             matlab.ui.control.DropDown
        RefChannelCDropDown             matlab.ui.control.DropDown
        RefChannelBDropDown             matlab.ui.control.DropDown
        RefChannelADropDown             matlab.ui.control.DropDown
        SignalDNameEditField            matlab.ui.control.EditField
        SignalCNameEditField            matlab.ui.control.EditField
        SignalBNameEditField            matlab.ui.control.EditField
        SignalANameEditField            matlab.ui.control.EditField
    end


    properties (Access = private)
        currentDir = fileparts(mfilename('fullpath'))
        channelIndex = {'A'; 'B'; 'C'; 'D'}
        defaultUigetdir = ''
        subjectID = ''
        TDTDir = ''
        EEGPath = ''
        TDTData = []
        loadedTDTDir = ''
        isosbesticChannels
        channelInfo
        nChannel
        eegFrequency
        fpFrequency
        signalLengthCut
        signalsCorrected
        eeg = []
        emg = []
        ttlOnset = 0
        eventData = {}
        eventChannel = 'none'
    end

    properties (Access = public)
        waitingForInput = false;
    end

    % methods that do not need app properties are stored in func
    % these are: 1) correct_fp_signal, 2) get_fp_onset, 3)
    % read_viewpoint_data, 4) sanitizeSignalNames, 5) align_viewpoint_data

    methods (Access = private)

        function TDTData = read_TDT_files(app)
            TDTData = TDTbin2mat(app.TDTDir);
            % Define the channels

            channels = fieldnames(TDTData.streams);
            app.isosbesticChannels = [];
            columns = {'channel', 'signalName', 'refChannel', 'samplingRate', 'invert'};
            columnTypes = {'string', 'string', 'string', 'double', 'logical'};
            app.channelInfo = table( ...
                'Size',[4, length(columns)], ...
                'RowNames', app.channelIndex, ...
                'VariableNames', columns, ...
                'VariableTypes', columnTypes ...
            );

            for i = 1:length(channels)
                channel = channels{i};
                % Extract the numeric digits from the channel string
                tokens = regexp(channel, '^x(\d+)([A-D]$)', 'tokens');
                if ~isempty(tokens)
                    wavelength = str2double(tokens{1}{1});
                    channelInd = tokens{1}{2};
                    if wavelength <= 420 % isosbestic channel
                        app.isosbesticChannels = [app.isosbesticChannels channels(i)];
                        app.channelInfo.refChannel(channelInd) = channel;
                    else
                        samplingRate = TDTData.streams.(channel).fs;
                        app.channelInfo.channel(channelInd) = channel;
                        app.channelInfo.samplingRate(channelInd) = samplingRate;
                    end
                end
            end

            % set default refChanne; for B and D
            matchA = find(endsWith(app.isosbesticChannels, 'A'));
            matchC = find(endsWith(app.isosbesticChannels, 'C'));
            % Handle duplicates / missing
            if isempty(matchA)
                error('No isosbestic channel in "A" found for refChannel B.');
            elseif numel(matchA) > 1
                warning('Multiple channels end with "A". Using the first: %s', app.isosbesticChannels{matchA(1)});
            end

            if isempty(matchC)
                error('No isosbestic channel in "C" found for refChannel D.');
            elseif numel(matchC) > 1
                warning('Multiple channels end with "C". Using the first: %s', app.isosbesticChannels{matchC(1)});
            end

            % Assign to app
            app.channelInfo.refChannel('B') = app.isosbesticChannels{matchA(1)};
            app.channelInfo.refChannel('D') = app.isosbesticChannels{matchC(1)};
        end

        function [] = display_TDT_channels(app, TDTData)
            % provide the option for not using a ref channel
            app.isosbesticChannels(end+1) = {'none'};
            for k = 1:numel(app.channelIndex)
                L = app.channelIndex{k};
                editFieldName = sprintf('Channel%sField', L);
                dropDownName = sprintf('RefChannel%sDropDown', L);
                app.(editFieldName).Value = app.channelInfo.channel(L);
                app.(dropDownName).Items = app.isosbesticChannels;
                app.(dropDownName).Value = app.channelInfo.refChannel(L);
            end

            % ttlChan
            ttlChannels = fieldnames(TDTData.epocs);
            ttlChannels{end+1} = 'none';
            app.TTLChannelDropDown.Items = ttlChannels;
            app.TTLChannelDropDown.Value = ttlChannels{1};
            app.EventPeriodChannelDropDown.Items = ttlChannels;
            app.EventPeriodChannelDropDown.Value = ttlChannels{end};
            app.ProgressPanel.Visible = 'off';
            app.ProgressTextArea.Value = {''};
            app.TDTBiosignalsPanel.Visible = 'on';
        end

        function [signalNamesAdded, signalNamesUnique] = add_signal_names(app)
            signalNamesAdded = false;
            signalNamesUnique = true;
            signalNames = strings(numel(app.channelIndex), 1);
            nSignalNames = 0;
            for k = 1:numel(app.channelIndex)
                L = app.channelIndex{k};
                editFieldName = sprintf('Signal%sNameEditField', L);
                checkBoxName = sprintf('Invert%sCheckBox', L);
                sigName = char(lower(strtrim(string(app.(editFieldName).Value))));
                invert = app.(checkBoxName).Value;
                app.channelInfo.signalName(L) = missing;
                app.channelInfo.invert(L) = invert;
                app.(editFieldName).Value = sigName;
                if ~isempty(sigName)
                    app.channelInfo.signalName(L) = sigName;
                    signalNamesAdded = true;
                    nSignalNames = nSignalNames + 1;
                    signalNames(nSignalNames) = sigName;
                end
            end

            if signalNamesAdded
                signalNames = signalNames(1:nSignalNames);
                formattedSignalNames = sanitizeSignalNames(signalNames);
                signalNamesUnique = numel(unique(formattedSignalNames)) == numel(formattedSignalNames);
            end
        end

        function signalsCorrected = process_fp_signal_parallel(app, signals, refSignals, signalsCorrected, signalChannels, invertSignals, onsetFPInd)
            q = parallel.pool.DataQueue;
            afterEach(q, @updateProgress);
            app.ProgressTextArea.Value{end+1} = 'Parallel computing available. Processing in parallel...';
            drawnow
            parfor i = 1:length(signalChannels)
                channel = signalChannels(i);
                refSignal = refSignals(i, :);
                refSignal = refSignal(onsetFPInd:end);
                signal = signals(i, :);
                signal = signal(onsetFPInd:end);
                invert = invertSignals(i);
                signalCorrected = correct_fp_signal(signal, refSignal, 'invert', invert);
                signalsCorrected(i, :) = signalCorrected;
                send(q, channel);
            end

            function updateProgress(channel)
                message = sprintf('Processed signal from %s.', channel);
                app.ProgressTextArea.Value{end+1} = message;
                drawnow
            end
        end

        function signalsCorrected = process_fp_signal(app, signals, refSignals, signalsCorrected, signalChannels, invertSignals, onsetFPInd)
            for i = 1:length(signalChannels)
                channel = signalChannels(i);
                refSignal = refSignals(i, :);
                refSignal = refSignal(onsetFPInd:end);
                signal = signals(i, :);
                signal = signal(onsetFPInd:end);
                invert = invertSignals(i);
                signalCorrected = correct_fp_signal(signal, refSignal, 'invert', invert);
                signalsCorrected(i, :) = signalCorrected;
                message = sprintf('Processed signal from %s.', channel);
                app.ProgressTextArea.Value{end+1} = message;
                drawnow;
            end
        end

        function signalsCorrected = process_fp_signals(app, TDTData)
            ttlChannel = app.TTLChannelDropDown.Value;
            app.ttlOnset = get_fp_onset(TDTData, ttlChannel);

            % extract labels if recorded in a channel in epocs in TDTData
            app.getEvent(TDTData, app.ttlOnset);

            app.fpFrequency = app.channelInfo.samplingRate(1);
            onsetFPInd = max(1, round(app.ttlOnset  *app.fpFrequency));
            app.channelInfo = rmmissing(app.channelInfo, 'DataVariables', 'signalName');
            signalChannels = app.channelInfo.channel;
            invertSignals = app.channelInfo.invert;
            streams = TDTData.streams;
            lengths = cellfun(@(ch) numel(streams.(ch).data), signalChannels);
            signalLength = min(lengths); % sometimes signals from diff chans vary in length

            if any(lengths ~= signalLength)
                lengthsStr = strjoin(string(lengths), ', ');
                message = sprintf('Signal channels differ in length. Min = %d, lengths = [%s]', signalLength, lengthsStr);
                app.ProgressTextArea.Value{end+1} = message;
            end

            %signalLength = length(TDTData.streams.(signalChannels(1)).data);
            app.signalLengthCut = signalLength - onsetFPInd + 1;
            app.nChannel = height(app.channelInfo);
            signals = zeros(app.nChannel, signalLength);
            refSignals = zeros(app.nChannel, signalLength);
            signalsCorrected = zeros(app.nChannel, app.signalLengthCut);
            for i = 1:app.nChannel
                channel = app.channelInfo.channel(i);
                refChannel = app.channelInfo.refChannel(i);
                signals(i,:) = TDTData.streams.(channel).data(1:signalLength);
                refSignals(i, :) = TDTData.streams.(refChannel).data(1:signalLength);
            end

            if length(signalChannels) > 1 && canUseParallelPool
                pool = gcp('nocreate');
                if isempty(pool)
                    parpool(2)
                end
                signalsCorrected = process_fp_signal_parallel(app, signals, refSignals, signalsCorrected, signalChannels, invertSignals, onsetFPInd);
            else
                signalsCorrected = process_fp_signal(app, signals, refSignals, signalsCorrected, signalChannels, invertSignals, onsetFPInd);
            end

        end


        function [] = process_selected_data(app)
            if ~isempty(app.TDTDir)
                app.signalsCorrected = process_fp_signals(app, app.TDTData);
                app.ProgressTextArea.Value{end+1} = 'Done processing data from TDT.';
                drawnow
            end

            if ~isempty(app.EEGPath)
                app.ProgressTextArea.Value{end+1} = 'Processing data from Viewpoint...';
                drawnow
                [app.eeg, app.emg] = process_viewpoint_data(app);
                app.ProgressTextArea.Value{end+1} = 'Done processing data from Viewpoint.';
            end
            app.SaveFileButton.Enable = 'on';
            app.SaveFileButton.Visible = 'on';
        end


        function [eeg, emg] = process_viewpoint_data(app)
            [viewpointData, info] = read_viewpoint_data(app.EEGPath);
            app.eegFrequency = info.Fs;
            [eeg, emg] = align_viewpoint_data(viewpointData, app.eegFrequency);
            eeg_start_time = [info.BinFiles.TStart];
            total_duration = length(eeg) / app.eegFrequency;
        end

        function processedSleepData = save_sleep_data(app)
            signalNames = app.channelInfo.signalName;
            signalNames = sanitizeSignalNames(signalNames);
            processedSleepData = cell2struct(mat2cell(app.signalsCorrected, ones(1,app.nChannel), app.signalLengthCut), cellstr(signalNames'), 1);
            processedSleepData.fp_signal_names = cellstr(signalNames);
            processedSleepData.eeg = app.eeg;
            processedSleepData.emg = app.emg;
            processedSleepData.fp_frequency = app.fpFrequency;
            processedSleepData.ttl_onset = app.ttlOnset;
            processedSleepData.eeg_frequency = app.eegFrequency;
            processedSleepData.event = app.eventData;
        end

        function [] = check_home_panel_input(app)
            if ~isempty(app.subjectID) && (~isempty(app.TDTDir) || ~isempty(app.EEGPath))
                app.ContinueButton.Enable = "on";
            else
                app.ContinueButton.Enable = "off";
            end
        end

        function [] = reset_app(app)
            app.TDTDir = '';
            app.EEGPath = '';
            app.TDTData = [];
            app.loadedTDTDir = '';
            app.HomePanel.Visible = 'on';
            app.ContinueButton.Enable = 'off';
            app.SaveFileButton.Enable = 'off';
            app.SaveFileButton.Visible = 'off';
            app.SubjectIDEditField.Value = '';
            app.SelectedTDTFolderTextArea.Value = '';
            app.SelectedEEGEMGPathTextArea.Value = '';
            app.ttlOnset = 0;
            app.eventData = {};
            app.eventChannel = 'none';
            for k = 1:numel(app.channelIndex)
                L = app.channelIndex{k};
                editFieldName = sprintf('Signal%sNameEditField', L);
                app.(editFieldName).Value = '';
            end
        end


        function [] = getEvent(app, TDTData, ttlOnset)
            if isempty(app.eventData)
                return
            end
            eventOnset = TDTData.epocs.(app.eventChannel).onset; % n x 1 double
            eventOffset = TDTData.epocs.(app.eventChannel).offset; % n x 1 double
            eventTime = [eventOnset eventOffset];
            eventTime = eventTime - ttlOnset;
            app.eventData{2} = eventTime;
            message = sprintf('Processed events from %s.', app.eventChannel);
            app.ProgressTextArea.Value{end+1} = message;
        end
    end


    % Callbacks that handle component events
    methods (Access = private)

        % Code that executes after component creation
        function startupFcn(app)
            addpath(fullfile(app.currentDir, 'func'), ...
                fullfile(app.currentDir, 'util'), ...
                fullfile(app.currentDir, 'EEGtoolbox') ...
            );
            reset_app(app);
        end

        % Button pushed function: AddTDTFolderButton
        function AddTDTFolderButtonPushed(app, event)
            f = figure('Position', [-100 -100 0 0]); % create a dummy figure so that uigetfile doesn't minimize our GUI
            selectedDir = uigetdir(app.defaultUigetdir);
            [parentFolder, ~, ~] = fileparts(string(selectedDir));
            app.defaultUigetdir = parentFolder;
            % Check if a directory was selected (uigetdir returns 0 if the user cancels the dialog)
            delete(f);
            if selectedDir ~= 0
                % Store the selected directory path in the Edit Field
                app.SelectedTDTFolderTextArea.Value = selectedDir;
                app.TDTDir = selectedDir; % ValueChaning callback is not triggered if changed programmatically
                check_home_panel_input(app); % so we need to manually check for input
            end

        end

        % Button pushed function: AddViewpointSireniaFileButton
        function AddViewpointSireniaFileButtonPushed(app, event)
            f = figure('Position', [-100 -100 0 0]); % create a dummy figure so that uigetfile doesn't minimize our GUI
            if ~isempty(app.defaultUigetdir)
                [selectedFile, parentFolder] = uigetfile({'*.exp; *.edf;'}, '', app.defaultUigetdir);
            else
            [selectedFile, parentFolder] = uigetfile({'*.exp; *.edf;'});
            end
            app.defaultUigetdir = parentFolder;
            % Check if a directory was selected (uigetdir returns 0 if the user cancels the dialog)
            delete(f);
            if selectedFile ~= 0
                % Store the selected directory path in the Edit Field
                app.SelectedEEGEMGPathTextArea.Value = fullfile(parentFolder, selectedFile);
                app.EEGPath = fullfile(parentFolder, selectedFile); % ValueChaning callback is not triggered if changed programmatically
                check_home_panel_input(app); % so we need to manually check for input
            end

        end

        % Button pushed function: ContinueButton2
        function ContinueButton2Pushed(app, event)
            [signalNameAdded, signalNamesUnique] = add_signal_names(app);
            title = 'Error';
            if ~signalNameAdded
                message = 'Please name at least one signal. Unnamed signals will not be saved.';
                uialert(app.UIFigure, message, title);
                return
            end
            if ~signalNamesUnique
                message = 'Signal names must be unique after formatting.';
                uialert(app.UIFigure, message, title);
                return
            end

            app.eventChannel = app.EventPeriodChannelDropDown.Value;
            if ~strcmp(app.eventChannel, 'none')
                eventName = regexprep(strtrim(app.EventPeriodNameEditField.Value), '\s+', '_');
                if isempty(eventName)
                    message = 'Please name the event/period.';
                    uialert(app.UIFigure, message, title);
                    return
                end
                app.eventData = {eventName, []};
            end

            app.TDTBiosignalsPanel.Visible = 'off';
            app.ProgressPanel.Visible = "on";
            app.ProgressTextArea.Value = {'Processing...'};
            drawnow;
            process_selected_data(app);
        end

        % Button pushed function: ContinueButton
        function ContinueButtonPushed(app, event)
            app.HomePanel.Visible = 'off';
            app.ProgressPanel.Visible = 'on';

            if ~isempty(app.TDTDir)
                pathChanged = isempty(app.loadedTDTDir) || ...
                    ~strcmpi(app.TDTDir, app.loadedTDTDir);
                if pathChanged || isempty(app.TDTData)
                    app.ProgressTextArea.Value = {'Reading TDT data... This may take a minute.'};
                    drawnow;
                    app.TDTData = read_TDT_files(app);
                    app.loadedTDTDir = app.TDTDir;
                    display_TDT_channels(app, app.TDTData);
                else
                    app.ProgressPanel.Visible = 'off';
                    app.TDTBiosignalsPanel.Visible = 'on';
                end
                return
            end

            app.ProgressTextArea.Value = {'Processing data...'};
            drawnow;
            process_selected_data(app);
        end

        % Button pushed function: SaveFileButton
        function SaveFileButtonPushed(app, event)
            f = figure('Position', [-100 -100 0 0]); % create a dummy figure so that uigetfile doesn't minimize our GUI
            %[~, name, ~] = fileparts(string(app.TDTDir));
            defaultSaveName = string(app.subjectID) + '.mat';
            [filename, path, ~] = uiputfile('*.mat', 'Save File', fullfile(app.defaultUigetdir, defaultSaveName));
            % Check if a directory was selected (uigetdir returns 0 if the user cancels the dialog)
            delete(f);
            if path ~= 0
                app.ProgressTextArea.Value{end+1} = 'Saving sleep data...';
                app.SaveFileButton.Enable = 'off';
                drawnow
                full_file_path = fullfile(path, filename);
                full_file_path = string(full_file_path);
                processedSleepData = save_sleep_data(app);
                save(full_file_path, '-struct', 'processedSleepData');

                message = strcat("Processed signals saved to ", full_file_path);
                title = 'File Saved';
                icon = 'success';
                uialert(app.UIFigure, message, title, 'Icon', icon);
                reset_app(app)
            end
        end

        % Value changing function: SubjectIDEditField
        function SubjectIDEditFieldValueChanging(app, event)
            value = event.Value;
            app.subjectID = char(value);
            app.SubjectIDLabel.Text = char(value);
            check_home_panel_input(app);
        end

        % Value changing function: SelectedTDTFolderTextArea
        function SelectedTDTFolderTextAreaValueChanging(app, event)
            value = event.Value;
            app.TDTDir = char(value);
            check_home_panel_input(app);
        end

        % Value changing function: SelectedEEGEMGPathTextArea
        function SelectedEEGEMGPathTextAreaValueChanging(app, event)
            value = event.Value;
            app.EEGPath = char(value);
            check_home_panel_input(app);
        end

        % Button pushed function: BackButton
        function BackButtonPushed(app, event)
            app.TDTBiosignalsPanel.Visible = 'off';
            app.HomePanel.Visible = 'on';
        end

        % Value changed function: EventPeriodChannelDropDown
        function EventPeriodChannelDropDownValueChanged(app, event)
            value = app.EventPeriodChannelDropDown.Value;
            if strcmp(value, 'none')
                app.EventPeriodNameEditField.Visible = "off";
                app.EventPeriodNameLabel.Visible = 'off';
            else
                app.EventPeriodNameEditField.Visible = "on";
                app.EventPeriodNameLabel.Visible = 'on';
            end
        end
    end

    % Component initialization
    methods (Access = private)

        % Create UIFigure and components
        function createComponents(app)

            % Create UIFigure and hide until all components are created
            app.UIFigure = uifigure('Visible', 'off');
            app.UIFigure.Position = [100 100 640 480];
            app.UIFigure.Name = 'MATLAB App';

            % Create TDTBiosignalsPanel
            app.TDTBiosignalsPanel = uipanel(app.UIFigure);
            app.TDTBiosignalsPanel.Title = 'TDT Biosignals';
            app.TDTBiosignalsPanel.Position = [101 44 440 394];

            % Create SignalANameEditField
            app.SignalANameEditField = uieditfield(app.TDTBiosignalsPanel, 'text');
            app.SignalANameEditField.Position = [156 274 67 22];

            % Create SignalBNameEditField
            app.SignalBNameEditField = uieditfield(app.TDTBiosignalsPanel, 'text');
            app.SignalBNameEditField.Position = [156 241 67 22];

            % Create SignalCNameEditField
            app.SignalCNameEditField = uieditfield(app.TDTBiosignalsPanel, 'text');
            app.SignalCNameEditField.Position = [156 207 67 22];

            % Create SignalDNameEditField
            app.SignalDNameEditField = uieditfield(app.TDTBiosignalsPanel, 'text');
            app.SignalDNameEditField.Position = [156 172 67 22];

            % Create RefChannelADropDown
            app.RefChannelADropDown = uidropdown(app.TDTBiosignalsPanel);
            app.RefChannelADropDown.Items = {'none'};
            app.RefChannelADropDown.Position = [260 274 74 22];
            app.RefChannelADropDown.Value = 'none';

            % Create RefChannelBDropDown
            app.RefChannelBDropDown = uidropdown(app.TDTBiosignalsPanel);
            app.RefChannelBDropDown.Items = {'none'};
            app.RefChannelBDropDown.Position = [260 241 74 22];
            app.RefChannelBDropDown.Value = 'none';

            % Create RefChannelCDropDown
            app.RefChannelCDropDown = uidropdown(app.TDTBiosignalsPanel);
            app.RefChannelCDropDown.Items = {'none'};
            app.RefChannelCDropDown.Position = [260 207 74 22];
            app.RefChannelCDropDown.Value = 'none';

            % Create RefChannelDDropDown
            app.RefChannelDDropDown = uidropdown(app.TDTBiosignalsPanel);
            app.RefChannelDDropDown.Items = {'none'};
            app.RefChannelDDropDown.Position = [260 172 74 22];
            app.RefChannelDDropDown.Value = 'none';

            % Create TTLChannelDropDown
            app.TTLChannelDropDown = uidropdown(app.TDTBiosignalsPanel);
            app.TTLChannelDropDown.Items = {'none'};
            app.TTLChannelDropDown.Position = [148 126 73 22];
            app.TTLChannelDropDown.Value = 'none';

            % Create EventPeriodChannelDropDown
            app.EventPeriodChannelDropDown = uidropdown(app.TDTBiosignalsPanel);
            app.EventPeriodChannelDropDown.Items = {'none'};
            app.EventPeriodChannelDropDown.ValueChangedFcn = createCallbackFcn(app, @EventPeriodChannelDropDownValueChanged, true);
            app.EventPeriodChannelDropDown.Position = [148 96 73 22];
            app.EventPeriodChannelDropDown.Value = 'none';

            % Create EventPeriodNameEditField
            app.EventPeriodNameEditField = uieditfield(app.TDTBiosignalsPanel, 'text');
            app.EventPeriodNameEditField.Visible = 'off';
            app.EventPeriodNameEditField.Placeholder = 'eg., foot shock';
            app.EventPeriodNameEditField.Position = [277 96 95 22];

            % Create ContinueButton2
            app.ContinueButton2 = uibutton(app.TDTBiosignalsPanel, 'push');
            app.ContinueButton2.ButtonPushedFcn = createCallbackFcn(app, @ContinueButton2Pushed, true);
            app.ContinueButton2.Position = [284 41 100 23];
            app.ContinueButton2.Text = 'Continue';

            % Create ReferenceChannelLabel
            app.ReferenceChannelLabel = uilabel(app.TDTBiosignalsPanel);
            app.ReferenceChannelLabel.HorizontalAlignment = 'center';
            app.ReferenceChannelLabel.FontWeight = 'bold';
            app.ReferenceChannelLabel.Position = [240 308 114 29];
            app.ReferenceChannelLabel.Text = 'Reference Channel';

            % Create SignalNameLabel
            app.SignalNameLabel = uilabel(app.TDTBiosignalsPanel);
            app.SignalNameLabel.HorizontalAlignment = 'center';
            app.SignalNameLabel.FontWeight = 'bold';
            app.SignalNameLabel.Position = [151 308 77 29];
            app.SignalNameLabel.Text = 'Signal Name';

            % Create BackButton
            app.BackButton = uibutton(app.TDTBiosignalsPanel, 'push');
            app.BackButton.ButtonPushedFcn = createCallbackFcn(app, @BackButtonPushed, true);
            app.BackButton.Tooltip = {'Oh no. What''s wrong?'};
            app.BackButton.Position = [53 42 58 23];
            app.BackButton.Text = 'Back';

            % Create SubjectIDLabel
            app.SubjectIDLabel = uilabel(app.TDTBiosignalsPanel);
            app.SubjectIDLabel.Tooltip = {'This is the Subject ID'};
            app.SubjectIDLabel.Position = [23 336 57 22];
            app.SubjectIDLabel.Text = '';

            % Create InvertLabel
            app.InvertLabel = uilabel(app.TDTBiosignalsPanel);
            app.InvertLabel.HorizontalAlignment = 'center';
            app.InvertLabel.FontWeight = 'bold';
            app.InvertLabel.Position = [360 308 43 29];
            app.InvertLabel.Text = 'Invert';

            % Create InvertACheckBox
            app.InvertACheckBox = uicheckbox(app.TDTBiosignalsPanel);
            app.InvertACheckBox.Text = '';
            app.InvertACheckBox.Position = [374 274 15 22];

            % Create InvertBCheckBox
            app.InvertBCheckBox = uicheckbox(app.TDTBiosignalsPanel);
            app.InvertBCheckBox.Text = '';
            app.InvertBCheckBox.Position = [374 241 15 22];

            % Create InvertCCheckBox
            app.InvertCCheckBox = uicheckbox(app.TDTBiosignalsPanel);
            app.InvertCCheckBox.Text = '';
            app.InvertCCheckBox.Position = [374 207 15 22];

            % Create InvertDCheckBox
            app.InvertDCheckBox = uicheckbox(app.TDTBiosignalsPanel);
            app.InvertDCheckBox.Text = '';
            app.InvertDCheckBox.Position = [374 172 15 22];

            % Create ChannelAEditFieldLabel_2
            app.ChannelAEditFieldLabel_2 = uilabel(app.TDTBiosignalsPanel);
            app.ChannelAEditFieldLabel_2.FontWeight = 'bold';
            app.ChannelAEditFieldLabel_2.Position = [17 274 64 22];
            app.ChannelAEditFieldLabel_2.Text = 'Channel A';

            % Create ChannelAField
            app.ChannelAField = uieditfield(app.TDTBiosignalsPanel, 'text');
            app.ChannelAField.Editable = 'off';
            app.ChannelAField.Position = [88 274 48 22];

            % Create ChannelBEditFieldLabel_2
            app.ChannelBEditFieldLabel_2 = uilabel(app.TDTBiosignalsPanel);
            app.ChannelBEditFieldLabel_2.FontWeight = 'bold';
            app.ChannelBEditFieldLabel_2.Position = [18 241 64 22];
            app.ChannelBEditFieldLabel_2.Text = 'Channel B';

            % Create ChannelBField
            app.ChannelBField = uieditfield(app.TDTBiosignalsPanel, 'text');
            app.ChannelBField.Editable = 'off';
            app.ChannelBField.Position = [88 241 48 22];

            % Create ChannelCEditFieldLabel_2
            app.ChannelCEditFieldLabel_2 = uilabel(app.TDTBiosignalsPanel);
            app.ChannelCEditFieldLabel_2.FontWeight = 'bold';
            app.ChannelCEditFieldLabel_2.Position = [19 207 64 22];
            app.ChannelCEditFieldLabel_2.Text = 'Channel C';

            % Create ChannelCField
            app.ChannelCField = uieditfield(app.TDTBiosignalsPanel, 'text');
            app.ChannelCField.Editable = 'off';
            app.ChannelCField.Position = [88 207 48 22];

            % Create ChannelDEditFieldLabel_2
            app.ChannelDEditFieldLabel_2 = uilabel(app.TDTBiosignalsPanel);
            app.ChannelDEditFieldLabel_2.FontWeight = 'bold';
            app.ChannelDEditFieldLabel_2.Position = [18 172 64 22];
            app.ChannelDEditFieldLabel_2.Text = 'Channel D';

            % Create ChannelDField
            app.ChannelDField = uieditfield(app.TDTBiosignalsPanel, 'text');
            app.ChannelDField.Editable = 'off';
            app.ChannelDField.Position = [88 172 48 22];

            % Create TTLChannelDropDown_2Label
            app.TTLChannelDropDown_2Label = uilabel(app.TDTBiosignalsPanel);
            app.TTLChannelDropDown_2Label.FontWeight = 'bold';
            app.TTLChannelDropDown_2Label.Position = [17 126 78 22];
            app.TTLChannelDropDown_2Label.Text = 'TTL Channel';

            % Create TTLChannelDropDown_2Label_2
            app.TTLChannelDropDown_2Label_2 = uilabel(app.TDTBiosignalsPanel);
            app.TTLChannelDropDown_2Label_2.FontWeight = 'bold';
            app.TTLChannelDropDown_2Label_2.Position = [18 96 132 22];
            app.TTLChannelDropDown_2Label_2.Text = 'Event/Period Channel';

            % Create Label
            app.Label = uilabel(app.TDTBiosignalsPanel);
            app.Label.FontSize = 8;
            app.Label.Position = [1 155 440 10];
            app.Label.Text = '--------------------------------------------------------------------------------------------------------------------------------------------------------------------';

            % Create EventPeriodNameLabel
            app.EventPeriodNameLabel = uilabel(app.TDTBiosignalsPanel);
            app.EventPeriodNameLabel.FontWeight = 'bold';
            app.EventPeriodNameLabel.Visible = 'off';
            app.EventPeriodNameLabel.Position = [240 96 38 22];
            app.EventPeriodNameLabel.Text = 'Name';

            % Create ProgressPanel
            app.ProgressPanel = uipanel(app.UIFigure);
            app.ProgressPanel.Title = 'Progress';
            app.ProgressPanel.Position = [101 44 440 394];

            % Create ProgressTextArea
            app.ProgressTextArea = uitextarea(app.ProgressPanel);
            app.ProgressTextArea.Position = [79 120 282 127];

            % Create SaveFileButton
            app.SaveFileButton = uibutton(app.ProgressPanel, 'push');
            app.SaveFileButton.ButtonPushedFcn = createCallbackFcn(app, @SaveFileButtonPushed, true);
            app.SaveFileButton.Enable = 'off';
            app.SaveFileButton.Visible = 'off';
            app.SaveFileButton.Position = [313 40 100 23];
            app.SaveFileButton.Text = 'Save File';

            % Create HomePanel
            app.HomePanel = uipanel(app.UIFigure);
            app.HomePanel.Title = 'Home';
            app.HomePanel.Position = [101 44 440 394];

            % Create AddTDTFolderButton
            app.AddTDTFolderButton = uibutton(app.HomePanel, 'push');
            app.AddTDTFolderButton.ButtonPushedFcn = createCallbackFcn(app, @AddTDTFolderButtonPushed, true);
            app.AddTDTFolderButton.Position = [28 172 108 37];
            app.AddTDTFolderButton.Text = 'Add TDT Folder';

            % Create AddViewpointSireniaFileButton
            app.AddViewpointSireniaFileButton = uibutton(app.HomePanel, 'push');
            app.AddViewpointSireniaFileButton.ButtonPushedFcn = createCallbackFcn(app, @AddViewpointSireniaFileButtonPushed, true);
            app.AddViewpointSireniaFileButton.WordWrap = 'on';
            app.AddViewpointSireniaFileButton.Position = [28 96 108 62];
            app.AddViewpointSireniaFileButton.Text = 'Add Viewpoint/Sirenia File';

            % Create SelectedTDTFolderTextArea
            app.SelectedTDTFolderTextArea = uitextarea(app.HomePanel);
            app.SelectedTDTFolderTextArea.ValueChangingFcn = createCallbackFcn(app, @SelectedTDTFolderTextAreaValueChanging, true);
            app.SelectedTDTFolderTextArea.Position = [156 172 257 36];

            % Create SelectedEEGEMGPathTextArea
            app.SelectedEEGEMGPathTextArea = uitextarea(app.HomePanel);
            app.SelectedEEGEMGPathTextArea.ValueChangingFcn = createCallbackFcn(app, @SelectedEEGEMGPathTextAreaValueChanging, true);
            app.SelectedEEGEMGPathTextArea.Position = [156 96 257 58];

            % Create ContinueButton
            app.ContinueButton = uibutton(app.HomePanel, 'push');
            app.ContinueButton.ButtonPushedFcn = createCallbackFcn(app, @ContinueButtonPushed, true);
            app.ContinueButton.Enable = 'off';
            app.ContinueButton.Position = [325 42 100 23];
            app.ContinueButton.Text = 'Continue';

            % Create SleepDataPreprocessingAppLabel
            app.SleepDataPreprocessingAppLabel = uilabel(app.HomePanel);
            app.SleepDataPreprocessingAppLabel.HorizontalAlignment = 'center';
            app.SleepDataPreprocessingAppLabel.FontSize = 18;
            app.SleepDataPreprocessingAppLabel.FontWeight = 'bold';
            app.SleepDataPreprocessingAppLabel.Position = [85 286 269 23];
            app.SleepDataPreprocessingAppLabel.Text = 'Sleep Data Preprocessing App';

            % Create SubjectIDEditFieldLabel
            app.SubjectIDEditFieldLabel = uilabel(app.HomePanel);
            app.SubjectIDEditFieldLabel.HorizontalAlignment = 'right';
            app.SubjectIDEditFieldLabel.FontWeight = 'bold';
            app.SubjectIDEditFieldLabel.Position = [69 225 64 22];
            app.SubjectIDEditFieldLabel.Text = 'Subject ID';

            % Create SubjectIDEditField
            app.SubjectIDEditField = uieditfield(app.HomePanel, 'text');
            app.SubjectIDEditField.ValueChangingFcn = createCallbackFcn(app, @SubjectIDEditFieldValueChanging, true);
            app.SubjectIDEditField.Position = [156 225 86 22];

            % Show the figure after all components are created
            app.UIFigure.Visible = 'on';
        end
    end

    % App creation and deletion
    methods (Access = public)

        % Construct app
        function app = app_exported

            % Create UIFigure and components
            createComponents(app)

            % Register the app with App Designer
            registerApp(app, app.UIFigure)

            % Execute the startup function
            runStartupFcn(app, @startupFcn)

            if nargout == 0
                clear app
            end
        end

        % Code that executes before app deletion
        function delete(app)

            % Delete UIFigure when app is deleted
            delete(app.UIFigure)
        end
    end
end